# Generated by Django 4.2 on 2023-04-08 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cineme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtimes', models.DateTimeField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Showtimes', to='movie_service.movies')),
            ],
        ),
    ]
