# Generated by Django 4.2 on 2023-04-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtimes',
            old_name='showtimes',
            new_name='starttime',
        ),
    ]
