# Generated by Django 4.2 on 2023-04-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0002_rename_showtimes_showtimes_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtimes',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
