# Generated by Django 4.2 on 2023-04-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_service', '0004_rename_movies_movie_rename_cineme_movie_cinema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
